name: Calculator Test Pipeline

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: [3.8, 3.9, "3.10", "3.11"]
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Debug - List files
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing all files:"
        ls -la
        echo "Listing week7 directory:"
        ls -la week7/
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        echo "Installing from week7/requirements.txt"
        pip install -r week7/requirements.txt
    
    - name: Run tests with pytest
      run: |
        echo "Running tests from week7/test_calculator.py"
        python -m pytest week7/test_calculator.py -v
    
    - name: Run tests with coverage
      run: |
        echo "Running coverage from week7/test_calculator.py"
        python -m pytest week7/test_calculator.py --cov=week7.calculator --cov-report=xml --cov-report=html

  lint:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Debug - List files
      run: |
        echo "Current directory: $(pwd)"
        echo "Listing all files:"
        ls -la
        echo "Listing week7 directory:"
        ls -la week7/
    
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: "3.11"
    
    - name: Install flake8
      run: |
        python -m pip install --upgrade pip
        pip install flake8
    
    - name: Lint with flake8
      run: |
        echo "Running flake8 on week7/calculator.py and week7/test_calculator.py"
        flake8 week7/calculator.py week7/test_calculator.py --count --select=E9,F63,F7,F82 --show-source --statistics
        flake8 week7/calculator.py week7/test_calculator.py --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
